name: Daily Release

# 触发条件：每天23:00或手动触发
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

# 设置权限
permissions:
  contents: write

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run crawler
        run: |
          python src/crawler.py

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: daily-${{ env.DATE }}
          name: "Comics Daily - ${{ env.DATE }}"
          body: |
            自动生成的漫画热门数据 (${{ env.DATE }})
            
            中文漫画:
            - 每日热门数据
            - 每周热门数据
            
            日文漫画:
            - 每日热门数据
            - 每周热门数据
            
            英文漫画:
            - 每日热门数据
            - 每周热门数据
          files: |
            output/chinese-comics-today-${{ env.DATE }}.json
            output/chinese-comics-week-${{ env.DATE }}.json
            output/japanese-comics-today-${{ env.DATE }}.json
            output/japanese-comics-week-${{ env.DATE }}.json
            output/english-comics-today-${{ env.DATE }}.json
            output/english-comics-week-${{ env.DATE }}.json
          draft: false
          prerelease: false
